# Generated by Django 4.2.6 on 2023-11-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Sessions',
            new_name='Session',
        ),
    ]
