# Generated by Django 4.2.6 on 2023-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0002_rename_courses_course_rename_sessions_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attended_sessions',
            field=models.ManyToManyField(null=True, to='inclass.session'),
        ),
        migrations.AlterField(
            model_name='student',
            name='elected_courses',
            field=models.ManyToManyField(null=True, to='inclass.course'),
        ),
    ]
