# Generated by Django 4.2.6 on 2023-11-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0003_alter_student_attended_sessions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attended_sessions',
            field=models.ManyToManyField(blank=True, null=True, to='inclass.session'),
        ),
    ]
