# Generated by Django 4.2.6 on 2023-11-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0005_alter_faculty_user_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attended_sessions',
            field=models.ManyToManyField(blank=True, to='inclass.session'),
        ),
        migrations.AlterField(
            model_name='student',
            name='elected_courses',
            field=models.ManyToManyField(to='inclass.course'),
        ),
    ]
