# Generated by Django 4.2.6 on 2023-11-07 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0006_alter_student_attended_sessions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
    ]
