# Generated by Django 4.2.6 on 2023-11-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0007_alter_faculty_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes_attended',
            options={'verbose_name': 'Classes Attended', 'verbose_name_plural': 'Classes Attended'},
        ),
        migrations.AlterModelOptions(
            name='total_classes',
            options={'verbose_name': 'Total Classes', 'verbose_name_plural': 'Total Classes'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
