# Generated by Django 4.2.6 on 2023-11-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0008_alter_classes_attended_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
