# Generated by Django 4.2.6 on 2023-11-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0009_alter_session_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclass.faculty'),
        ),
    ]
