# Generated by Django 4.2.6 on 2023-11-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0011_rename_course_session_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_classes',
            name='total_classes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
