# Generated by Django 4.2.6 on 2023-11-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0012_alter_total_classes_total_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='elected_courses',
            field=models.ManyToManyField(blank=True, to='inclass.course'),
        ),
    ]
