# Generated by Django 4.2.6 on 2023-11-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0013_alter_student_elected_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes_attended',
            name='classes_attended',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
