# Generated by Django 4.2.6 on 2023-11-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0014_alter_classes_attended_classes_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attended_sessions',
            field=models.ManyToManyField(blank=True, related_name='attended_students', to='inclass.session'),
        ),
    ]
