# Generated by Django 4.2.6 on 2023-11-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0015_alter_student_attended_sessions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes_attended',
            old_name='roll_no',
            new_name='student',
        ),
    ]
