# Generated by Django 4.2.6 on 2023-11-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0016_rename_roll_no_classes_attended_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='elective',
            field=models.BooleanField(default=False),
        ),
    ]
