# Generated by Django 4.2.6 on 2023-11-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0017_course_elective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='elected_courses',
            field=models.ManyToManyField(blank=True, related_name='students_elected', to='inclass.course'),
        ),
    ]
