# Generated by Django 4.2.6 on 2023-11-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclass', '0019_alter_total_classes_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='total_classes',
            name='batch',
            field=models.CharField(max_length=4),
        ),
    ]
